spring:
  thymeleaf:
    encoding: utf-8
    mode: HTML5
    servlet:
      content-type: text/html
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://jiakongkeji.cn:3307/security?useSSL=false
    username: root
    password: press
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
server:
  port: 1996
